server:
  port: 8081
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml   #mybatis配置文件所在路径
  type-aliases-package: com.yuanqiao.entities     #所有entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  application:
    name: swaggerdemo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    dbcp2:
      min-idle: 5         #数据库连接池的最小维持连接数
      initial-size: 5      #初始化连接数
      max-total: 5            #最大连接数
      max-wait-millis: 200      #等待连接获取的最大超时时间






















